# Generated by Django 2.1.1 on 2018-10-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Honey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['ip'], 'verbose_name': 'Contact-Mails'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='objet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='mdp',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
