# Generated by Django 2.1.1 on 2018-10-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Honey', '0002_auto_20181017_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['ip'], 'verbose_name': 'Login de connexion'},
        ),
    ]
