# Generated by Django 2.1.1 on 2018-10-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Honey', '0003_auto_20181017_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='mdp',
            field=models.CharField(max_length=32),
        ),
    ]
