# Generated by Django 2.1.1 on 2018-10-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Honey', '0006_auto_20181017_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='mdp',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
