# Generated by Django 2.1.1 on 2018-10-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Honey', '0007_auto_20181017_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
